// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoDTbsXJNfPgua42fAJ8lwzL27XEJKmzo',
    appId: '1:928979492934:web:0068650e0bebf6d1266a47',
    messagingSenderId: '928979492934',
    projectId: 'healthcare-6657b',
    authDomain: 'healthcare-6657b.firebaseapp.com',
    storageBucket: 'healthcare-6657b.appspot.com',
    measurementId: 'G-5PHHSFBP04',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3j_NcyMhn6nZlq8PdfP6owXv0XiYEtzs',
    appId: '1:928979492934:android:45ebde2a69dab05c266a47',
    messagingSenderId: '928979492934',
    projectId: 'healthcare-6657b',
    storageBucket: 'healthcare-6657b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAqAxjM63ZSTw5_zjdHWAhKl1VFcVvrM8',
    appId: '1:928979492934:ios:cc98424549e5bc3b266a47',
    messagingSenderId: '928979492934',
    projectId: 'healthcare-6657b',
    storageBucket: 'healthcare-6657b.appspot.com',
    iosClientId:
        '928979492934-d6ih5ks88jiuvtrj5vtit51aj4qt9uvc.apps.googleusercontent.com',
    iosBundleId: 'com.example.hospitalAppointment',
  );
}
