// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm9yt-2xjS7xxXhzN4I2jhCYXMxbnm1Bs',
    appId: '1:561754184188:web:1342a5aef8c38684eefa79',
    messagingSenderId: '561754184188',
    projectId: 'csse-project-healthcare-app',
    authDomain: 'csse-project-healthcare-app.firebaseapp.com',
    storageBucket: 'csse-project-healthcare-app.appspot.com',
    measurementId: 'G-Z50TS0PYWV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYZTlNBqI3gIQwvnd8atdcQoBM3JHPH88',
    appId: '1:561754184188:android:eefaee100dcbf185eefa79',
    messagingSenderId: '561754184188',
    projectId: 'csse-project-healthcare-app',
    storageBucket: 'csse-project-healthcare-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_34OqHbBOlJxBI7o4vjyvRkq8F7YAcWg',
    appId: '1:561754184188:ios:8b2a4c88a10dda85eefa79',
    messagingSenderId: '561754184188',
    projectId: 'csse-project-healthcare-app',
    storageBucket: 'csse-project-healthcare-app.appspot.com',
    iosBundleId: 'com.example.smartHealthcareSystem',
  );
}
